author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["natu"]
sitelen_emosi = ""
sitelen_pona = ["aka"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "aka"

[[etymology]]
alt = "guò"
word = "过"

[[etymology]]
word = "across"

[luka_pona]

[recognition]
2022-08 = 0
2023-09 = 1
