author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🦎"
sitelen_pona = ["akesi", "akesi2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/akesi.jpg"
source_language = "Dutch"
ucsur = "U+F1901"
usage_category = "core"
word = "akesi"

[[etymology]]
word = "hagedis"

[ku_data]
frog = 56
reptile = 96

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/akesi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/akesi.mp4"

[pu_verbatim]
de = "NOMEN nichtsüßes Tier; Reptil, Amphibie"
en = "NOUN non-cute animal; reptile, amphibian"
eo = "SUBSTANTIVO reptilio, amfibio"
fr = "NOM animal non-mignon ; reptile, amphibien"

[recognition]
2022-08 = 98
2023-09 = 99
