author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = ""
coined_year = ""
etymology = []
see_also = ["a"]
sitelen_emosi = ""
sitelen_pona = ["ako"]
sitelen_sitelen = ""
source_language = "unknown"
ucsur = ""
usage_category = "obscure"
word = "ako"

[luka_pona]

[recognition]
2022-08 = 0
2023-09 = 0
