"$schema" = "../../schemas/generated/word.json"
author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = ""
coined_year = ""
creator = []
etymology = []
see_also = ["a"]
source_language = "unknown"
usage_category = "obscure"
word = "ako"

[audio]
kala_asi = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/ako.mp3"

[recognition]
2022-08 = 0
2023-09 = 0

[representations]
sitelen_emosi = ""
sitelen_pona = ["ako"]
sitelen_sitelen = ""
ucsur = ""
