author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "❌"
sitelen_pona = ["ala"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ala.jpg"
source_language = "Georgian"
ucsur = "U+F1902"
usage_category = "core"
word = "ala"

[[etymology]]
alt = "ara"
word = "არა"

[ku_data]
hardly = 28
neither = 60
no = 94
none = 100
nor = 30
not = 100
nothing = 81
zero = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/ala.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/ala.mp4"

[pu_verbatim]
de = "ADJEKTIV nein, nicht, kein, nichts, Null"
en = "ADJECTIVE no, not, zero"
eo = "ADJEKTIVO ne, nul"
fr = "ADJECTIF non, ne, pas, aucun, zéro"

[recognition]
2022-08 = 100
2023-09 = 100
