author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = []
source_language = "toki pona"
usage_category = "obscure"
word = "alente"

[[etymology]]
word = "ale ante"

[recognition]
2022-08 = 2
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["alente"]
sitelen_sitelen = ""
ucsur = ""
