author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["alente"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "alente"

[luka_pona]

[recognition]
2022-08 = 2
2023-09 = 2
