author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["ale"]
source_language = "Dutch"
usage_category = "uncommon"
word = "ali"

[[etymology]]
word = "alle"

[ku_data]
all = 32
entire = 27
universe = 21

[recognition]
2022-08 = 35
2023-09 = 32

[representations]
sitelen_emosi = "♾️"
sitelen_pona = ["ali"]
sitelen_sitelen = ""
ucsur = ""
