author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["ale"]
sitelen_emosi = "♾️"
sitelen_pona = ["ali"]
sitelen_sitelen = ""
source_language = "Dutch"
ucsur = ""
usage_category = "uncommon"
word = "ali"

[ku_data]
all = 32
entire = 27
universe = 21

[luka_pona]

[recognition]
2022-08 = 35
2023-09 = 32
