author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2018"
see_also = ["la"]
sitelen_emosi = ""
sitelen_pona = ["alu"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "alu"

[[etymology]]
word = "la"

[luka_pona]

[recognition]
2020-04 = 18
2021-10 = 24
2022-08 = 3
2023-09 = 3
