author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2018"
see_also = ["la"]
source_language = "toki pona"
usage_category = "obscure"
word = "alu"

[[etymology]]
word = "la"

[recognition]
2020-04 = 18
2021-10 = 24
2022-08 = 3
2023-09 = 3

[representations]
sitelen_emosi = ""
sitelen_pona = ["alu"]
sitelen_sitelen = ""
ucsur = ""
