author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["sama"]
sitelen_emosi = "🔀"
sitelen_pona = ["ante"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ante.jpg"
source_language = "Dutch"
ucsur = "U+F1906"
usage_category = "core"
word = "ante"

[[etymology]]
word = "ander"

[ku_data]
adapt = 40
adaptation = 25
adjust = 37
adjustment = 42
affect = 40
alter = 94
alternative = 76
amendment = 36
another = 47
change = 75
changing = 100
contrast = 55
conversion = 46
convert = 75
counterpart = 29
difference = 71
different = 100
differently = 69
distinct = 69
distinction = 55
distinguish = 37
diversity = 26
edit = 73
else = 47
modify = 90
opposed = 33
other = 100
replace = 50
separate = 30
shift = 25
switch = 50
transform = 60
transformation = 70
transition = 33
unlike = 33
variation = 60
vary = 67

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/ante.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/ante.mp4"

[pu_verbatim]
de = "ADJEKTIV unterschiedlich, verändert, modifiziert, anders"
en = "ADJECTIVE different, altered, changed, other"
eo = "ADJEKTIVO malsama, ŝanĝita, alia"
fr = "ADJECTIF différent, changé, autre"

[recognition]
2022-08 = 99
2023-09 = 99
