author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "☯️"
sitelen_pona = ["anu"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/anu.jpg"
source_language = "Georgian"
ucsur = "U+F1907"
usage_category = "core"
word = "anu"

[ku_data]
choice = 47
decide = 31
either = 31
or = 100
select = 31
selection = 36
whether = 60

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/anu.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/anu.mp4"

[pu_verbatim]
de = "PARTIKEL oder"
en = "PARTICLE or"
eo = "PARTIKULO aŭ"
fr = "PARTICULE ou"

[recognition]
2022-08 = 98
2023-09 = 99
