author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2009"
see_also = ["pilin"]
source_language = "Finnish"
usage_category = "uncommon"
word = "apeja"

[[etymology]]
word = "häpeä"

[ku_data]
embarrassed = 27
guilt = 17
shame = 40

[recognition]
2020-04 = 44
2021-10 = 59
2022-08 = 20
2023-09 = 23

[representations]
sitelen_emosi = "😢"
sitelen_pona = ["apeja"]
sitelen_sitelen = ""
ucsur = "U+F19A1"
