author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["utala", "pakala", "tawa", "anpa"]
sitelen_emosi = ""
sitelen_pona = ["awase"]
sitelen_sitelen = ""
source_language = "Armenian"
ucsur = ""
usage_category = "obscure"
word = "awase"

[luka_pona]

[recognition]
2022-08 = 0
2023-09 = 1
