author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["utala", "pakala", "tawa", "anpa"]
source_language = "Armenian"
usage_category = "obscure"
word = "awase"

[[etymology]]
alt = "harvacel"
word = "հարվածել"

[recognition]
2022-08 = 0
2023-09 = 1

[representations]
sitelen_emosi = ""
sitelen_pona = ["awase"]
sitelen_sitelen = ""
ucsur = ""
