author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
source_language = "a priori"
usage_category = "core"
word = "e"

[[etymology]]

[pu_verbatim]
de = "PARTIKEL (vor dem direkten Objekt)"
en = "PARTICLE (before the direct object)"
eo = "PARTIKULO (emfazo, emocio aŭ konfirmo)"
fr = "PARTICULE (avant l'objet direct)"

[recognition]
2022-08 = 100
2023-09 = 100

[representations]
sitelen_emosi = "⏩"
sitelen_pona = ["e"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/e.jpg"
ucsur = "U+F1909"
