author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["natu"]
sitelen_emosi = ""
sitelen_pona = ["eki"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "eki"

[[etymology]]
word = "x (letter name)"

[luka_pona]

[recognition]
2022-08 = 0
2023-09 = 1
