author_verbatim = "distress, affliction, adversity, pain"
author_verbatim_source = "https://discord.com/channels/301377942062366741/375591429608570881/1072666397626335242"
book = "none"
coined_era = "post-ku"
coined_year = ""
see_also = ["utala", "pilin", "ike"]
sitelen_emosi = ""
sitelen_pona = []
sitelen_sitelen = ""
source_language = "Tsalagi"
ucsur = ""
usage_category = "obscure"
word = "eliki"

[[etymology]]
word = "ehisdi"

[recognition]
2023-09 = 3
