author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "➕"
sitelen_pona = ["en"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/en.jpg"
source_language = "Dutch"
ucsur = "U+F190A"
usage_category = "core"
word = "en"

[[etymology]]
word = "en"

[ku_data]
and = 50
plus = 50

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/en.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/en.mp4"

[pu_verbatim]
de = "PARTIKEL (zwischen mehreren Subjekten)"
en = "PARTICLE (between multiple subjects)"
eo = "PARTIKULO (inter pluraj subjektoj)"
fr = "PARTICULE (entre plusieurs sujets)"

[recognition]
2022-08 = 98
2023-09 = 99
