author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["lon", "ma"]
source_language = "toki pona"
usage_category = "obscure"
word = "enko"

[[etymology]]
word = "tenpo"

[recognition]
2021-10 = 28
2022-08 = 4
2023-09 = 4

[representations]
sitelen_emosi = "🧭"
sitelen_pona = ["enko", "enko2"]
sitelen_sitelen = ""
ucsur = ""
