author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["suli", "sewi", "wawa"]
sitelen_emosi = "🔃"
sitelen_pona = ["ete", "ete2"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "ete"

[[etymology]]
word = "öte"

[ku_data]
beyond = 14
exceed = 20

[luka_pona]

[recognition]
2020-04 = 17
2021-10 = 33
2022-08 = 5
2023-09 = 4
