author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["kiwen"]
sitelen_emosi = "🌋"
sitelen_pona = ["ewe"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "ewe"

[ku_data]
stone = 3

[luka_pona]

[recognition]
2020-04 = 11
2021-10 = 28
2022-08 = 2
2023-09 = 1
