author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["kiwen"]
source_language = "multiple"
usage_category = "obscure"
word = "ewe"

[[etymology]]
alt = "iwa"
word = "岩"

[[etymology]]
word = "kiwen"

[ku_data]
stone = 3

[recognition]
2020-04 = 11
2021-10 = 28
2022-08 = 2
2023-09 = 1

[representations]
sitelen_emosi = "🌋"
sitelen_pona = ["ewe"]
sitelen_sitelen = ""
ucsur = ""
