author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2002"
see_also = ["ona"]
sitelen_emosi = ""
sitelen_pona = ["i"]
sitelen_sitelen = ""
source_language = "unknown"
ucsur = ""
usage_category = "obscure"
word = "i"

[[etymology]]
word = "unknown"

[luka_pona]

[recognition]
2022-08 = 1
2023-09 = 1
