author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🐚"
sitelen_pona = ["ijo"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ijo.jpg"
source_language = "Esperanto"
ucsur = "U+F190C"
usage_category = "core"
word = "ijo"

[[etymology]]
word = "io"

[ku_data]
anything = 50
asset = 33
being = 33
chemical = 32
element = 38
entity = 82
example = 25
item = 100
material = 63
"matter (n)" = 62
object = 100
phenomenon = 67
product = 29
something = 100
stock = 27
stuff = 100
subject = 30
substance = 53
thing = 100

[pu_verbatim]
de = "NOMEN Ding, Phänomen, Objekt, Angelegenheit"
en = "NOUN thing, phenomenon, object, matter"
eo = "SUBSTANTIVO aĵo, fenomeno, objekto, afero"
fr = "NOM chose, phénomène, objet, matière"

[recognition]
2022-08 = 99
2023-09 = 100
