author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["ona"]
sitelen_emosi = ""
sitelen_pona = ["iki"]
sitelen_sitelen = ""
source_language = "unknown"
ucsur = ""
usage_category = "obscure"
word = "iki"

[luka_pona]

[recognition]
2020-04 = 15
2021-10 = 21
2022-08 = 1
2023-09 = 1
