author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["ona"]
source_language = "unknown"
usage_category = "obscure"
word = "iki"

[[etymology]]
word = "unknown"

[recognition]
2020-04 = 15
2021-10 = 21
2022-08 = 1
2023-09 = 1

[representations]
sitelen_emosi = ""
sitelen_pona = ["iki"]
sitelen_sitelen = ""
ucsur = ""
