author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "⏺️"
sitelen_pona = ["insa"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/insa.jpg"
source_language = "Tok Pisin"
ucsur = "U+F190F"
usage_category = "core"
word = "insa"

[[etymology]]
word = "insait"

[ku_data]
amid = 27
belly = 54
between = 27
central = 60
centre = 91
content = 27
core = 67
guts = 71
inner = 100
insert = 31
inside = 58
interior = 93
internal = 100
"internal organ" = 38
middle = 56
stomach = 41
within = 35

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/insa.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/insa.mp4"

[pu_verbatim]
de = "NOMEN Zentrum, Inhalt, Inneres, zwischen; inneres Organ, Magen"
en = "NOUN centre, content, inside, between; internal organ, stomach"
eo = "SUBSTANTIVO centro, enhavo, eno, inter; ena organo, ventro, stomako"
fr = "NOM centre, contenu, intérieur, entre ; estomac, viscères"

[recognition]
2022-08 = 99
2023-09 = 100
