author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2002"
see_also = ["ona"]
sitelen_emosi = ""
sitelen_pona = ["ipi"]
sitelen_sitelen = ""
source_language = "unknown"
ucsur = ""
usage_category = "obscure"
word = "ipi"

[luka_pona]

[recognition]
2020-04 = 13
2021-10 = 19
2022-08 = 1
2023-09 = 1
