author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2002"
see_also = ["ona"]
source_language = "unknown"
usage_category = "obscure"
word = "ipi"

[[etymology]]
word = "unknown"

[recognition]
2020-04 = 13
2021-10 = 19
2022-08 = 1
2023-09 = 1

[representations]
sitelen_emosi = ""
sitelen_pona = ["ipi"]
sitelen_sitelen = ""
ucsur = ""
