author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
sitelen_emosi = "😈"
sitelen_pona = ["itomi"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "itomi"

[luka_pona]

[recognition]
2020-04 = 17
2021-10 = 19
2022-08 = 1
2023-09 = 1
