author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2018"
see_also = ["mute", "ale"]
sitelen_emosi = ""
sitelen_pona = ["jaku"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "obscure"
word = "jaku"

[[etymology]]
alt = "hyaku"
word = "百"

[recognition]
2020-04 = 14
2021-10 = 18
2022-08 = 1
2023-09 = 1
