author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2002"
see_also = ["noka"]
sitelen_emosi = ""
sitelen_pona = ["jalan"]
sitelen_sitelen = ""
source_language = "Finnish"
ucsur = ""
usage_category = "obscure"
word = "jalan"

[[etymology]]
word = "jalan"

[luka_pona]

[recognition]
2020-04 = 13
2021-10 = 20
2022-08 = 1
2023-09 = 1
