author_verbatim = "also tp needs a specific interjection (i.e. not a or kin) for \"yum\""
author_verbatim_source = "https://discord.com/channels/301377942062366741/301382587287339018/353665304569839616"
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["suwi", "pilin"]
sitelen_emosi = "🤤"
sitelen_pona = ["jami"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "jami"

[luka_pona]

[recognition]
2021-10 = 29
2022-08 = 5
2023-09 = 6
