author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = ""
see_also = ["a", "wa"]
sitelen_emosi = ""
sitelen_pona = ["je"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "je"

[luka_pona]

[recognition]
2021-10 = 20
2022-08 = 1
2023-09 = 3
