author_verbatim = "hjönk 🦢"
author_verbatim_source = "https://discord.com/channels/301377942062366741/599425762990358528/825733377465778176"
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["mu", "nja"]
sitelen_emosi = ""
sitelen_pona = ["jonke"]
sitelen_sitelen = ""
source_language = "onomatopoeia"
ucsur = ""
usage_category = "obscure"
word = "jonke"

[[etymology]]
word = "hjönk"

[luka_pona]

[recognition]
2022-08 = 3
2023-09 = 5
