author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = ["tawa", "poka"]
source_language = "Japanese"
usage_category = "obscure"
word = "jule"

[[etymology]]
alt = "yureru"
word = "揺れる"

[recognition]
2022-08 = 1
2023-09 = 4

[representations]
sitelen_emosi = ""
sitelen_pona = ["jule"]
sitelen_sitelen = ""
ucsur = ""
