author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = ["tawa", "poka"]
sitelen_emosi = ""
sitelen_pona = ["jule"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "obscure"
word = "jule"

[luka_pona]

[recognition]
2022-08 = 1
2023-09 = 4
