author_verbatim = "isipin is kinda dumb so here's a better nimisin: jume, dream"
author_verbatim_source = "https://discord.com/channels/301377942062366741/301377942062366741/803447186255642624"
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["oni", "sitelen", "lape", "insa", "powe"]
sitelen_emosi = ""
sitelen_pona = ["jume"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "obscure"
word = "jume"

[luka_pona]

[recognition]
2021-10 = 17
2022-08 = 1
2023-09 = 3
