author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
source_language = "Serbo-Croatian"
usage_category = "core"
word = "kalama"

[[etymology]]
alt = "galama"
word = "галама"

[ku_data]
bang = 27
noise = 79
sound = 100
tone = 50

[pu_verbatim]
de = "VERB Geräusche machen; vortragen, laut aussprechen"
en = "VERB to produce a sound; recite, utter aloud"
eo = "VERBO fari sonon; reciti, diri laŭte aŭ voĉe"
fr = "VERBE émettre un son ; réciter, proférer"

[recognition]
2022-08 = 99
2023-09 = 100

[representations]
sitelen_emosi = "🔈"
sitelen_pona = ["kalama"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kalama.jpg"
ucsur = "U+F1915"
