author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🐟"
sitelen_pona = ["kala", "kala2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kala.jpg"
source_language = "Finnish"
ucsur = "U+F1914"
usage_category = "core"
word = "kala"

[ku_data]
fish = 100
salmon = 62
"sea creature" = 82

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kala.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kala.mp4"

[pu_verbatim]
de = "NOMEN Fisch, Seetier, Meerestier"
en = "NOUN fish, marine animal, sea creature"
eo = "SUBSTANTIVO fiŝo, mara besto, mara vivaĵo"
fr = "NOM poisson, animal sous-marin"

[recognition]
2022-08 = 99
2023-09 = 99
