author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["kalama"]
sitelen_emosi = ""
sitelen_pona = ["kalamARR"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "kalamARR"

[luka_pona]

[recognition]
2020-04 = 13
2022-08 = 4
2023-09 = 4
