author_verbatim = "member of the order Caryophyllales, including all cacti as well as carnations, beets, and many carnivorous plants"
author_verbatim_source = "https://discord.com/channels/301377942062366741/337299887869657090/731769293699809300"
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["kijetesantakalu"]
sitelen_emosi = ""
sitelen_pona = ["kalijopilale"]
sitelen_sitelen = ""
source_language = "Latin"
ucsur = ""
usage_category = "obscure"
word = "kalijopilale"

[[etymology]]
word = "Caryophyllales"

[recognition]
2022-08 = 1
2023-09 = 2
