author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🚶"
sitelen_pona = ["kama"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kama.jpg"
source_language = "Tok Pisin"
ucsur = "U+F1916"
usage_category = "core"
word = "kama"

[[etymology]]
word = "kamap"

[ku_data]
arise = 33
arrival = 90
arrive = 88
become = 78
come = 91
coming = 93
developmental = 33
emerge = 67
emerging = 69
event = 27
happen = 62
induce = 31
next = 36
occur = 54
phenomenon = 27
trigger = 29
upcoming = 71
visit = 31

[luka_pona]

[pu_verbatim]
de = "ADJEKTIV ankommend, kommend, zukünftig, vorgeladen, beschworen\nHILFSVERB etw. werden, etw. schaffen, etw. erreichen"
en = "ADJECTIVE arriving, coming, future, summoned\nPRE-VERB to become, manage to, succeed in"
eo = "ADJEKTIVO alvenanta, venonta, estonteca, venigita\nANTAŬVERBO iĝi, sukcesi, elturniĝi pri"
fr = "ADJECTIF qui arrive, qui vent, futur, venu\nAUXILIAIRE devenir, arriver à, réussir à"

[recognition]
2022-08 = 99
2023-09 = 100
