author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2018"
see_also = []
sitelen_emosi = "💣"
sitelen_pona = ["kamalawala"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "rare"
word = "kamalawala"

[[etymology]]
word = "kama pi lawa ala"

[ku_data]
revolution = 7

[luka_pona]

[recognition]
2020-04 = 21
2021-10 = 29
2022-08 = 8
2023-09 = 10
