author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["kepeken", "poka", "en"]
source_language = "multiple possibilities"
usage_category = "obscure"
word = "kan"

[[etymology]]
word = "kanssa"

[ku_data]
alongside = 17
amid = 7
associated = 9
involved = 8
together = 16
with = 13

[recognition]
2020-04 = 22
2021-10 = 34
2022-08 = 7
2023-09 = 4

[representations]
sitelen_emosi = "🔗"
sitelen_pona = ["kan"]
sitelen_sitelen = ""
ucsur = ""
