author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["nena"]
sitelen_emosi = ""
sitelen_pona = ["kapa"]
sitelen_sitelen = ""
source_language = "multiple possibilities"
ucsur = ""
usage_category = "obscure"
word = "kapa"

[[etymology]]
word = "kop"

[recognition]
2020-04 = 13
2021-10 = 20
2022-08 = 2
2023-09 = 1
