author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["pimeja"]
sitelen_emosi = "🟤"
sitelen_pona = ["kapesi", "kapesi2"]
sitelen_sitelen = ""
source_language = "multiple possibilities"
ucsur = ""
usage_category = "rare"
word = "kapesi"

[[etymology]]
alt = "gaa³ fe¹ sik¹"
word = "咖啡色"

[[etymology]]
alt = "kāfēisè"
word = "咖啡色"

[ku_data]
brown = 24
grey = 7

[luka_pona]

[recognition]
2020-04 = 29
2021-10 = 45
2022-08 = 14
2023-09 = 19
