author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🌴"
sitelen_pona = ["kasi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kasi.jpg"
source_language = "Finnish"
ucsur = "U+F1917"
usage_category = "core"
word = "kasi"

[ku_data]
bush = 61
herb = 40
plant = 95
tree = 32

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kasi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kasi.mp4"

[pu_verbatim]
de = "NOMEN Pflanze, Vegetation; Kraut, Blatt"
en = "NOUN plant, vegetation; herb, leaf"
eo = "SUBSTANTIVO planto, vegetaĵo; herbo, folio"
fr = "NOM plante, végétation ; herbe, feuille"

[recognition]
2022-08 = 99
2023-09 = 100
