author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🔧"
sitelen_pona = ["kepeken"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kepeken.jpg"
source_language = "Dutch"
ucsur = "U+F1919"
usage_category = "core"
word = "kepeken"

[ku_data]
employ = 50
equip = 25
interact = 26
operate = 27
use = 93
used = 40
utilize = 75
via = 60

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kepeken.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kepeken.mp4"

[pu_verbatim]
de = "PRÄPOSITION mittels, benutzen, mithilfe von, mit Hilfe"
en = "PREPOSITION to use, with, by means of"
eo = "PREPOZICIO uzi, per, uzante"
fr = "PRÉPOSITION en utilisant, avec, au moyen de"

[recognition]
2022-08 = 99
2023-09 = 100
