author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["kepeken"]
sitelen_emosi = ""
sitelen_pona = ["kepeken"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "kepen"

[[etymology]]
word = "kepeken"

[luka_pona]

[recognition]
2022-08 = 1
2023-09 = 3
