author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["ki"]
sitelen_sitelen = ""
source_language = "French"
ucsur = ""
usage_category = "obscure"
word = "ki"

[[etymology]]
word = "qui"

[luka_pona]

[recognition]
2021-10 = 23
2022-08 = 2
2023-09 = 2
