author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["kipisi"]
sitelen_emosi = ""
sitelen_pona = ["kiki"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "uncommon"
word = "kiki"

[[etymology]]

[ku_data]
angle = 8
point = 6
sharp = 14
spiky = 21

[recognition]
2021-10 = 41
2022-08 = 21
2023-09 = 29
