author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["a"]
sitelen_emosi = "❕"
sitelen_pona = ["kin"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kin.jpg"
source_language = "Finnish"
ucsur = "U+F1979"
usage_category = "widespread"
word = "kin"

[ku_data]
also = 79
especially = 25
indeed = 25
too = 73

[luka_pona]

[pu_verbatim]
de = "PARTIKEL (Betonung, Emotion oder Bestätigung)"
en = "PARTICLE (emphasis, emotion or confirmation)"
eo = "PARTIKULO (emfazo, emocio aŭ konfirmo)"
fr = "PARTICULE (accent, émotion ou confirmation)"

[recognition]
2020-04 = 91
2021-10 = 97
2022-08 = 89
2023-09 = 83
