author_verbatim = "cat"
author_verbatim_source = "https://discord.com/channels/301377942062366741/599425762990358528/835188367871311902"
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["soweli"]
sitelen_emosi = ""
sitelen_pona = ["kisa"]
sitelen_sitelen = ""
source_language = "Russian"
ucsur = ""
usage_category = "obscure"
word = "kisa"

[luka_pona]

[recognition]
2021-10 = 24
2022-08 = 1
2023-09 = 4
