author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🍦"
sitelen_pona = ["ko"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ko.jpg"
source_language = "Cantonese"
ucsur = "U+F191C"
usage_category = "core"
word = "ko"

[[etymology]]
alt = "gou"
word = "膏"

[ku_data]
clay = 60
cream = 33
dough = 30
dust = 36
goo = 88
mud = 28
paste = 73
powder = 73
sand = 38
semisolid = 86
substance = 33

[pu_verbatim]
de = "NOMEN Lehm, Haftendes, Knete, Teig, Halbfestes, Paste, Puder"
en = "NOUN clay, clinging form, dough, semi-solid, paste, powder"
eo = "SUBSTANTIVO argilo, kunteniĝanta aŭ glueca formo, pasto, duonsolidaĵo, pulvoro"
fr = "NOM argle, pâte, poudre, substance collante, semi-solide"

[recognition]
2022-08 = 98
2023-09 = 99
