author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "💨"
sitelen_pona = ["kon"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kon.jpg"
source_language = "Mandarin"
ucsur = "U+F191D"
usage_category = "core"
word = "kon"

[[etymology]]
alt = "kōngqì"
word = "空氣"

[ku_data]
abstract = 33
air = 100
atmosphere = 64
breath = 57
breathe = 60
breathing = 45
breeze = 33
definition = 34
essence = 65
gas = 83
intangible = 53
"invisible entity" = 45
meaning = 55
oxygen = 60
smell = 29
soul = 100
spirit = 86

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kon.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kon.mp4"

[pu_verbatim]
de = "NOMEN Luft, Atem; Essenz, Geist; versteckte Realität, ungesehener Akteur"
en = "NOUN air, breath; essence, spirit, hidden reality, unseen agent"
eo = "SUBSTANTIVO aero, spiro; esenco, spirito; kaŝita realaĵo, io nevidata"
fr = "NOM air, souffle ; essence, esprit ; réalité cachée, agent invisible"

[recognition]
2022-08 = 99
2023-09 = 99
