author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = ""
coined_year = ""
see_also = []
sitelen_emosi = ""
sitelen_pona = ["konsi"]
sitelen_sitelen = ""
source_language = "Korean"
ucsur = ""
usage_category = "obscure"
word = "konsi"

[[etymology]]
alt = "gongji"
word = "공지"

[recognition]
2022-08 = 0
2023-09 = 1
