author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["ma", "tenpo"]
source_language = "multiple"
usage_category = "obscure"
word = "konwe"

[[etymology]]
word = "Conway"

[recognition]
2021-10 = 25
2022-08 = 6
2023-09 = 7

[representations]
sitelen_emosi = ""
sitelen_pona = ["konwe"]
sitelen_sitelen = ""
ucsur = ""
