author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["ma", "tenpo"]
sitelen_emosi = ""
sitelen_pona = ["konwe"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "konwe"

[luka_pona]

[recognition]
2021-10 = 25
2022-08 = 6
2023-09 = 7
