author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["awen"]
sitelen_emosi = ""
sitelen_pona = ["kosan"]
sitelen_sitelen = ""
source_language = "Irish"
ucsur = ""
usage_category = "obscure"
word = "kosan"

[[etymology]]
word = "cosain"

[luka_pona]

[recognition]
2022-08 = 1
2023-09 = 2
