author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["awen"]
source_language = "Irish"
usage_category = "obscure"
word = "kosan"

[[etymology]]
word = "cosain"

[recognition]
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["kosan"]
sitelen_sitelen = ""
ucsur = ""
