author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["pu"]
sitelen_emosi = ""
sitelen_pona = ["ku"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = "U+F1988"
usage_category = "widespread"
word = "ku"

[[etymology]]

[recognition]
2021-10 = 85
2022-08 = 80
2023-09 = 70
