author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🌈"
sitelen_pona = ["kule"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kule.jpg"
source_language = "Acadian French"
ucsur = "U+F191E"
usage_category = "core"
word = "kule"

[[etymology]]
word = "couleur"

[ku_data]
"LGBTQ+" = 35
colour = 100
diverse = 36
gay = 30
lesbian = 30
paint = 33
spectrum = 27

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kule.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kule.mp4"

[pu_verbatim]
de = "ADJEKTIV bunt, pigmentiert, gemalt"
en = "ADJECTIVE colourful, pigmented, painted"
eo = "ADJEKTIVO kolora, pigmenta, pentrita"
fr = "ADJECTIF coloré, pigmenté, peint"

[recognition]
2022-08 = 99
2023-09 = 99
