author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["oke"]
source_language = "English"
usage_category = "obscure"
word = "kulijo"

[[etymology]]
word = "coolio"

[recognition]
2021-10 = 28
2022-08 = 6
2023-09 = 7

[representations]
sitelen_emosi = ""
sitelen_pona = ["kulijo"]
sitelen_sitelen = ""
ucsur = ""
