author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["kulupu"]
source_language = "toki pona"
usage_category = "obscure"
word = "kulu"

[[etymology]]
word = "kulupu"

[recognition]
2020-04 = 14
2021-10 = 19
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["kulu"]
sitelen_sitelen = ""
ucsur = ""
