author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2018"
see_also = []
sitelen_emosi = "🤣"
sitelen_pona = ["kuntu"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "kuntu"

[ku_data]
chuckle = 13
comedy = 8
laugh = 8
laughter = 14

[luka_pona]

[recognition]
2020-04 = 21
2021-10 = 31
2022-08 = 7
2023-09 = 3
