author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "👂"
sitelen_pona = ["kute"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/kute.jpg"
source_language = "Acadian French"
ucsur = "U+F1920"
usage_category = "core"
word = "kute"

[ku_data]
ear = 90
hear = 100
hearing = 89
listen = 93

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/kute.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/kute.mp4"

[pu_verbatim]
de = "NOMEN Ohr\nVERB hören, zuhören; aufpassen, gehorchen"
en = "NOUN ear\nVERB to hear, listen; pay attention to, obey"
eo = "SUBSTANTIVO orelo\nVERBO aŭdi, aŭskulti; atenti, obei"
fr = "NOM oreille\nVERBE entendre, écouter ; faire attention à, obéir"

[recognition]
2022-08 = 99
2023-09 = 100
