author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["kutopoma"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "kutopoma"

[luka_pona]

[recognition]
2022-08 = 0
2023-09 = 0
