author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["jo", "alasa"]
source_language = "Greek"
usage_category = "common"
word = "lanpan"

[[etymology]]
alt = "lamváno"
word = "λαμβάνω"

[ku_data]
grab = 25
seize = 42
steal = 48

[recognition]
2020-04 = 28
2021-10 = 71
2022-08 = 52
2023-09 = 58

[representations]
sitelen_emosi = "📥"
sitelen_pona = ["lanpan", "lanpan3"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/lanpan.jpg"
ucsur = "U+F1985"
