author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = ""
coined_year = ""
see_also = []
source_language = "Korean"
usage_category = "obscure"
word = "lijokuku"

[[etymology]]
alt = "realkk"
word = "ㄹㅇㅋㅋ"

[recognition]
2022-08 = 0
2023-09 = 0

[representations]
sitelen_emosi = ""
sitelen_pona = ["lijokuku", "lijokuku2"]
sitelen_sitelen = ""
ucsur = ""
