"$schema" = "../../schemas/generated/word.json"
author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = ""
coined_year = ""
see_also = []
source_language = "Korean"
usage_category = "obscure"
word = "lijokuku"

[[etymology]]
alt = "realkk"
word = "ㄹㅇㅋㅋ"

[audio]
kala_asi = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/lijokuku.mp3"

[recognition]
2022-08 = 0
2023-09 = 0

[representations]
sitelen_emosi = ""
sitelen_pona = ["lijokuku", "lijokuku2"]
sitelen_sitelen = ""
ucsur = ""
