author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2018"
see_also = ["kulupu", "alasa"]
sitelen_emosi = "🧺"
sitelen_pona = ["likujo"]
sitelen_sitelen = ""
source_language = "Acadian French"
ucsur = ""
usage_category = "obscure"
word = "likujo"

[[etymology]]
word = "recueil"

[ku_data]
collection = 3
gathering = 7
seven = 7

[recognition]
2020-04 = 13
2021-10 = 25
2022-08 = 3
2023-09 = 4
