author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["len", "ilo", "wan"]
sitelen_emosi = "🌐"
sitelen_pona = ["linluwi", "linluwi2"]
sitelen_sitelen = ""
source_language = "Welsh"
ucsur = ""
usage_category = "uncommon"
word = "linluwi"

[[etymology]]
word = "rhyngrwyd"

[ku_data]
Internet = 15
connection = 8
digital = 8
net = 7
network = 25
virtual = 13
web = 9

[recognition]
2020-04 = 31
2021-10 = 55
2022-08 = 29
2023-09 = 34
