author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🔴"
sitelen_pona = ["loje"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/loje.jpg"
source_language = "Dutch"
ucsur = "U+F192B"
usage_category = "core"
word = "loje"

[[etymology]]
word = "rooie"

[ku_data]
red = 95

[pu_verbatim]
de = "ADJEKTIV rot, rötlich"
en = "ADJECTIVE red, reddish"
eo = "ADJEKTIVO ruĝa, ruĝeca"
fr = "ADJECTIF rouge"

[recognition]
2022-08 = 98
2023-09 = 99
