author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["luka", "noka"]
sitelen_emosi = ""
sitelen_pona = ["loka"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "loka"

[ku_data]
limb = 13

[luka_pona]

[recognition]
2021-10 = 22
2022-08 = 2
2023-09 = 1
