author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["luka", "noka"]
source_language = "toki pona"
usage_category = "obscure"
word = "loka"

[[etymology]]
word = "luka & noka"

[ku_data]
limb = 13

[recognition]
2021-10 = 22
2022-08 = 2
2023-09 = 1

[representations]
sitelen_emosi = ""
sitelen_pona = ["loka"]
sitelen_sitelen = ""
ucsur = ""
