author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["pu", "ku"]
sitelen_emosi = ""
sitelen_pona = ["lu"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "obscure"
word = "lu"

[[etymology]]

[luka_pona]

[recognition]
2021-10 = 29
2022-08 = 1
2023-09 = 1
