author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["noka"]
sitelen_emosi = "✋"
sitelen_pona = ["luka"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/luka.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F192D"
usage_category = "core"
word = "luka"

[ku_data]
arm = 68
elbow = 25
five = 64
gesture = 27
hand = 100
handful = 29
palm = 32
reach = 25
tap = 26
touch = 33
wrist = 50

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/luka.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/luka.mp4"

[pu_verbatim]
de = "NOMEN Arm, Hand, Tastorgan\nZAHL Fünf"
en = "NOUN arm, hand, tactile organ\nNUMBER five"
eo = "SUBSTANTIVO brako, mano, tuŝorgano\nNOMBRO kvin"
fr = "NOM bras, main, organe du toucher\nNOMBRE cinq"

[recognition]
2022-08 = 99
2023-09 = 100
