author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🕳️"
sitelen_pona = ["lupa"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/lupa.jpg"
source_language = "Lojban"
ucsur = "U+F192F"
usage_category = "core"
word = "lupa"

[ku_data]
dig = 21
door = 87
entrance = 40
gap = 27
gate = 45
hole = 94
opening = 27
orifice = 79
pit = 77
window = 57

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/lupa.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/lupa.mp4"

[pu_verbatim]
de = "NOMEN Tür, Loch, Öffnung, Fenster"
en = "NOUN door, hole, orifice, window"
eo = "SUBSTANTIVO pordo, truo, korpa aperturo, fenestro"
fr = "NOM porte, trou, orifice, fenêtre"

[recognition]
2022-08 = 98
2023-09 = 99
