author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "<2001"
see_also = ["suli", "tenpo"]
sitelen_emosi = "👵"
sitelen_pona = ["majuna", "majuna2"]
sitelen_sitelen = ""
source_language = "Esperanto"
ucsur = "U+F19A2"
usage_category = "uncommon"
word = "majuna"

[[etymology]]
word = "maljuna"

[ku_data]
ancient = 17
elder = 15
elderly = 36
historical = 20
old = 33
senior = 21

[recognition]
2020-04 = 38
2021-10 = 59
2022-08 = 32
2023-09 = 34
