author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["kule", "meli"]
sitelen_emosi = "👩‍❤️‍👩"
sitelen_pona = ["melome"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "melome"

[[etymology]]
word = "meli pi olin meli"

[luka_pona]

[recognition]
2020-04 = 25
2021-10 = 36
2022-08 = 7
2023-09 = 7
