author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["insa"]
sitelen_emosi = ""
sitelen_pona = ["meso", "meso2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/meso.jpg"
source_language = "Greek"
ucsur = "U+F1982"
usage_category = "common"
word = "meso"

[[etymology]]
alt = "mésos"
word = "μέσος"

[ku_data]
average = 53
intermediate = 29
medium = 47
moderate = 50
ordinary = 29

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/meso.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/meso.mp4"

[recognition]
2021-10 = 71
2022-08 = 52
2023-09 = 52
