author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["meli", "tonsi"]
sitelen_emosi = "👨"
sitelen_pona = ["mije", "mije2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/mije.jpg"
source_language = "Finnish"
ucsur = "U+F1935"
usage_category = "widespread"
word = "mije"

[ku_data]
boyfriend = 29
"cisgender man" = 50
gentleman = 24
guy = 29
husband = 55
male = 94
man = 90
sir = 35
"transgender man" = 18

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/mije.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/mije.mp4"

[pu_verbatim]
de = "NOMEN Mann, Männchen, maskuline Person; Ehemann"
en = "NOUN man, male, masculine person; husband"
eo = "SUBSTANTIVO viro, virseksulo; edzo"
fr = "NOM homme, mâle ; mari"

[recognition]
2022-08 = 89
2023-09 = 82
