author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["kule", "mije"]
source_language = "toki pona"
usage_category = "obscure"
word = "mijomi"

[[etymology]]
word = "mije pi olin mije"

[recognition]
2020-04 = 25
2021-10 = 35
2022-08 = 7
2023-09 = 7

[representations]
sitelen_emosi = "👨‍❤️‍👨"
sitelen_pona = ["mijomi"]
sitelen_sitelen = ""
ucsur = ""
