author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "pre-pu"
coined_year = "2001-2009"
see_also = ["moku"]
sitelen_emosi = "💊"
sitelen_pona = ["misikeke"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/misikeke.jpg"
source_language = "Ojibwe"
ucsur = "U+F1987"
usage_category = "common"
word = "misikeke"

[ku_data]
cure = 40
medical = 30
medication = 46
medicine = 42
pill = 30

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/misikeke.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/misikeke.mp4"

[recognition]
2020-04 = 21
2021-10 = 71
2022-08 = 63
2023-09 = 60
