author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🍽️"
sitelen_pona = ["moku"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/moku.jpg"
source_language = "Japanese"
ucsur = "U+F1936"
usage_category = "core"
word = "moku"

[[etymology]]
alt = "mogumogu"
word = "モグモグ"

[ku_data]
absorb = 35
chew = 44
consume = 97
consumption = 83
dining = 88
dinner = 50
drink = 27
drinking = 47
eat = 100
eating = 100
food = 100
groceries = 43
lunch = 26
meal = 83
nutrition = 50
swallow = 68

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/moku.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/moku.mp4"

[pu_verbatim]
de = "VERB essen, trinken, konsumieren, schlucken, einnehmen"
en = "VERB to eat, drink, consume, swallow, ingest"
eo = "VERBO manĝi, trinki, konsumi, gluti"
fr = "VERBE manger, boire, consommer, avaler"

[recognition]
2022-08 = 100
2023-09 = 100
