author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["pini"]
sitelen_emosi = "💀"
sitelen_pona = ["moli"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/moli.jpg"
source_language = "Acadian French"
ucsur = "U+F1937"
usage_category = "core"
word = "moli"

[[etymology]]
word = "mourir"

[ku_data]
dead = 94
deadly = 38
death = 100
die = 75
dying = 69
execution = 27
kill = 64
killing = 100

[pu_verbatim]
de = "ADJEKTIV tot, sterbend"
en = "ADJECTIVE dead, dying"
eo = "ADJEKTIVO mortinta, mortanta"
fr = "ADJECTIF mort, mourant"

[recognition]
2022-08 = 99
2023-09 = 99
