author_verbatim = "hm i am considering making a nimisin for mollusks, if that isn’t already a thing"
author_verbatim_source = "https://discord.com/channels/301377942062366741/301377942062366741/861476478021533696"
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["pipi"]
sitelen_emosi = ""
sitelen_pona = ["molusa"]
sitelen_sitelen = ""
source_language = "multiple"
ucsur = ""
usage_category = "obscure"
word = "molusa"

[luka_pona]

[recognition]
2021-10 = 25
2022-08 = 3
2023-09 = 4
