author_verbatim = "mulapisu now means pizza"
author_verbatim_source = "https://discord.com/channels/301377942062366741/301377942062366741/640770414431174676"
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["pan"]
sitelen_emosi = "🍕"
sitelen_pona = ["mulapisu"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "obscure"
word = "mulapisu"

[[etymology]]

[ku_data]
pizza = 40

[recognition]
2020-04 = 32
2021-10 = 39
2022-08 = 7
2023-09 = 6
