author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["suno"]
sitelen_emosi = "🌙"
sitelen_pona = ["mun"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/mun.jpg"
source_language = "English"
ucsur = "U+F193A"
usage_category = "core"
word = "mun"

[[etymology]]
word = "moon"

[ku_data]
"celestial body" = 80
moon = 95
planet = 19
star = 25

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/mun.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/mun.mp4"

[pu_verbatim]
de = "NOMEN Mond, Objekt am Nachthimmel, Stern"
en = "NOUN moon, night sky object, star"
eo = "SUBSTANTIVO luno, nokta ĉiela objekto, stelo"
fr = "NOM lune, astre, étoile"

[recognition]
2022-08 = 99
2023-09 = 99
