author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["a"]
sitelen_emosi = ""
sitelen_pona = ["n"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/n.jpg"
source_language = "onomatopoeia"
ucsur = "U+F1986"
usage_category = "widespread"
word = "n"

[[etymology]]

[ku_data]
hmm = 33
mmm = 40
um = 47

[recognition]
2021-10 = 60
2022-08 = 68
2023-09 = 70
