author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["loje", "jelo"]
sitelen_emosi = ""
sitelen_pona = ["nalanja"]
sitelen_sitelen = ""
source_language = "Spanish"
ucsur = ""
usage_category = "obscure"
word = "nalanja"

[[etymology]]
word = "naranja"

[luka_pona]

[recognition]
2022-08 = 1
2023-09 = 3
