author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["loje", "jelo"]
source_language = "Spanish"
usage_category = "obscure"
word = "nalanja"

[[etymology]]
word = "naranja"

[recognition]
2022-08 = 1
2023-09 = 3

[representations]
sitelen_emosi = ""
sitelen_pona = ["nalanja"]
sitelen_sitelen = ""
ucsur = ""
