author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🛣️"
sitelen_pona = ["nasin"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/nasin.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F193F"
usage_category = "core"
word = "nasin"

[ku_data]
aisle = 44
angle = 25
avenue = 80
channel = 32
composition = 25
course = 55
custom = 45
direction = 73
doctrine = 92
format = 52
guideline = 39
ideology = 50
journey = 44
lane = 43
layout = 56
manner = 80
method = 91
mode = 69
norm = 40
order = 33
orientation = 70
passage = 54
path = 83
pattern = 28
plan = 33
policy = 25
procedure = 35
process = 54
protocol = 33
regular = 38
road = 100
route = 75
routine = 31
strategy = 30
street = 71
style = 39
system = 56
tactic = 48
technique = 67
tendency = 25
theme = 27
track = 53
trail = 70
way = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/nasin.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/nasin.mp4"

[pu_verbatim]
de = "NOMEN Art und Weise, Brauch, Doktrin, Methode, Weg, Pfad, Straße"
en = "NOUN way, custom, doctrine, method, path, road"
eo = "SUBSTANTIVO maniero, kutimo, doktrino, metodo, vojo, irejo"
fr = "NOM chemin, voie ; manière, façon ; coutume, méthode, doctrine"

[recognition]
2022-08 = 99
2023-09 = 100
