author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["wan", "sama", "linja"]
sitelen_emosi = ""
sitelen_pona = ["natu"]
sitelen_sitelen = ""
source_language = "Vietnamese"
ucsur = ""
usage_category = "obscure"
word = "natu"

[[etymology]]
word = "ngã tư"

[luka_pona]

[recognition]
2021-10 = 25
2022-08 = 3
2023-09 = 3
