author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["neja"]
sitelen_sitelen = ""
source_language = "Finnish"
ucsur = ""
usage_category = "obscure"
word = "neja"

[luka_pona]

[recognition]
2020-04 = 13
2021-10 = 23
2022-08 = 2
2023-09 = 1
