author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["ona"]
sitelen_emosi = "👇"
sitelen_pona = ["ni", "ni2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ni.jpg"
source_language = "Cantonese"
ucsur = "U+F1941"
usage_category = "core"
word = "ni"

[[etymology]]
alt = "ni"
word = "呢"

[[etymology]]
alt = "le"
word = "哩"

[ku_data]
particular = 31
specifically = 27
that = 86
there = 25
these = 83
this = 100
those = 77

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/ni.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/ni.mp4"

[pu_verbatim]
de = "ADJEKTIV diese, dieser, dieses, jene, jener, jenes"
en = "ADJECTIVE that, this"
eo = "ADJEKTIVO (ĉi) tiu, (ĉi) tio"
fr = "ADJECTIF ce, cette"

[recognition]
2022-08 = 100
2023-09 = 100
