author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "💬"
sitelen_pona = ["nimi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/nimi.jpg"
source_language = "Finnish"
ucsur = "U+F1942"
usage_category = "core"
word = "nimi"

[ku_data]
brand = 29
label = 33
lyrics = 40
name = 100
so-called = 29
term = 55
title = 50
word = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/nimi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/nimi.mp4"

[pu_verbatim]
de = "NOMEN Name, Wort"
en = "NOUN name, word"
eo = "SUBSTANTIVO nomo, vorto"
fr = "NOM mot, nom"

[recognition]
2022-08 = 99
2023-09 = 100
