author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["nimi", "sin"]
sitelen_emosi = ""
sitelen_pona = ["nimisin"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "uncommon"
word = "nimisin"

[[etymology]]
word = "nimi sin"

[luka_pona]

[recognition]
2022-08 = 13
2023-09 = 35
