author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["mu", "jonke"]
sitelen_emosi = ""
sitelen_pona = ["nja"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "obscure"
word = "nja"

[[etymology]]
alt = "nyā"
word = "ニャー"

[recognition]
2022-08 = 5
2023-09 = 9
