author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["luka"]
sitelen_emosi = "🦵"
sitelen_pona = ["noka"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/noka.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F1943"
usage_category = "core"
word = "noka"

[ku_data]
ankle = 50
base = 31
foot = 67
heel = 38
kick = 43
knee = 33
lap = 55
leg = 93

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/noka.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/noka.mp4"

[pu_verbatim]
de = "NOMEN Fuß, Bein, Fortbewegungsorgan; Unterseite, Unterteil"
en = "NOUN foot, leg, organ of locomotion; bottom, lower part"
eo = "SUBSTANTIVO piedo, kruro, moviĝa organo; malsupro, malsupra"
fr = "NOM pied, jambe, organe de locomotion ; bas, dessous"

[recognition]
2022-08 = 98
2023-09 = 99
