author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["li"]
sitelen_emosi = "👋"
sitelen_pona = ["o"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/o.jpg"
source_language = "Georgian"
ucsur = "U+F1944"
usage_category = "core"
word = "o"

[ku_data]
dare = 9
dear = 6
hey = 50
let = 10
mandate = 9
must = 24
ought = 29
please = 16
shall = 42
should = 37

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/o.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/o.mp4"

[pu_verbatim]
de = "PARTIKEL hey! O! (Vokativ oder Imperativ)"
en = "PARTICLE hey! O! (vocative or imperative)"
eo = "PARTIKULO he! (vokativo aŭ imperativo)"
fr = "PARTICULE hé ! ô ! (vocatif ou impératif)"

[recognition]
2022-08 = 100
2023-09 = 100
