author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
source_language = "toki pona"
usage_category = "obscure"
word = "ojuta"

[[etymology]]
word = "o uta"

[recognition]
2022-08 = 2
2023-09 = 6

[representations]
sitelen_emosi = ""
sitelen_pona = ["ojuta"]
sitelen_sitelen = ""
ucsur = ""
