author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["pona", "ke", "n", "a"]
sitelen_emosi = "👌"
sitelen_pona = ["oke"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "uncommon"
word = "oke"

[[etymology]]
word = "okay"

[ku_data]
OK = 10
alright = 9
fine = 7

[luka_pona]

[recognition]
2020-04 = 25
2021-10 = 40
2022-08 = 16
2023-09 = 24
