author_verbatim = "interjection \"okay boomer\""
author_verbatim_source = "https://discord.com/channels/301377942062366741/545467374254555137/641341684982218752"
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
sitelen_emosi = "🦖"
sitelen_pona = ["okepuma"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "okepuma"

[[etymology]]
word = "okay boomer"

[luka_pona]

[recognition]
2020-04 = 21
2021-10 = 24
2022-08 = 3
2023-09 = 2
