author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["oki"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "oki"

[[etymology]]
word = "okie"

[recognition]
2022-08 = 1
2023-09 = 4
