author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "💕"
sitelen_pona = ["olin", "olin2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/olin.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F1945"
usage_category = "core"
word = "olin"

[[etymology]]
alt = "volim"
word = "волим"

[ku_data]
appreciation = 13
attraction = 40
beloved = 27
care = 14
compassion = 50
crush = 13
darling = 16
dear = 17
faithful = 20
intimate = 33
love = 96
loving = 100
loyal = 20
loyalty = 23
mercy = 16
passion = 29
passionate = 16
respect = 13
romance = 69
romantic = 60

[pu_verbatim]
de = "VERB lieben, Mitgefühl haben, respektieren, Zuneigung zeigen"
en = "VERB to love, have compassion for, respect, show affection to"
eo = "VERBO ami, simpatii kun, respekti, montri sian korinklinon al"
fr = "VERBE aimer, respecter, compatir, montrer de l'affection pour"

[recognition]
2022-08 = 99
2023-09 = 100
