author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["omekapo"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "uncommon"
word = "omekapo"

[[etymology]]
word = "o moku e kala pona"

[luka_pona]

[recognition]
2021-10 = 38
2022-08 = 16
2023-09 = 20
