author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["omekalike"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "omekalike"

[[etymology]]
word = "o moku e kala ike"

[luka_pona]

[recognition]
2022-08 = 5
2023-09 = 3
