author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["musi"]
sitelen_emosi = "🙄"
sitelen_pona = ["omen"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "omen"

[[etymology]]
word = "o moli e mi"

[luka_pona]

[recognition]
2020-04 = 19
2021-10 = 19
2022-08 = 1
2023-09 = 2
