author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["insa", "lape", "musi", "sitelen", "jume"]
source_language = "Ancient Greek"
usage_category = "obscure"
word = "oni"

[[etymology]]
alt = "oneiroi"
word = "ὄνειροι"

[recognition]
2021-10 = 26
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["oni", "oni2"]
sitelen_sitelen = ""
ucsur = ""
