author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["kama"]
sitelen_emosi = "🔓"
sitelen_pona = ["open"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/open.jpg"
source_language = "English"
ucsur = "U+F1947"
usage_category = "core"
word = "open"

[[etymology]]
word = "open"

[ku_data]
access = 36
begin = 100
beginning = 82
engage = 33
entry = 36
initial = 40
initiate = 73
introduction = 25
launch = 33
open = 100
opening = 60
origin = 25
start = 91
starter = 32
starting = 69

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/open.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/open.mp4"

[pu_verbatim]
de = "VERB beginnen, starten; öffnen; anschalten"
en = "VERB to begin, start; open; turn on"
eo = "VERBO komenci; malfermi; ŝalti"
fr = "VERBE commencer, ouvrir, allumer"

[recognition]
2022-08 = 99
2023-09 = 100
