author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
source_language = "English"
usage_category = "obscure"
word = "pa"

[[etymology]]
word = "bruh"

[recognition]
2020-04 = 21
2021-10 = 21
2022-08 = 3
2023-09 = 3

[representations]
sitelen_emosi = "🤨"
sitelen_pona = ["pa"]
sitelen_sitelen = ""
ucsur = ""
