author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = []
source_language = "toki pona"
usage_category = "obscure"
word = "pakola"

[[etymology]]
word = "pakala"

[recognition]
2023-09 = 3

[representations]
sitelen_emosi = ""
sitelen_pona = []
sitelen_sitelen = ""
ucsur = ""
