author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["moku"]
sitelen_emosi = "🍞"
sitelen_pona = ["pan"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/pan.jpg"
source_language = "multiple"
ucsur = "U+F194B"
usage_category = "core"
word = "pan"

[[etymology]]
word = "pan"

[[etymology]]
alt = "pan"
word = "パン"

[[etymology]]
word = "pão"

[ku_data]
bread = 100
carbohydrate = 25
corn = 30
grain = 81
rice = 53
wheat = 67

[pu_verbatim]
de = "NOMEN Getreide, Korn; Gerste, Mais, Hafer, Reis, Weizen; Brot, Nudeln"
en = "NOUN cereal, grain; barley, corn, oat, rice, wheat; bread, pasta"
eo = "SUBSTANTIVO greno, cerealo; aveno, hordeo, maizo, rizo, tritiko; pano, pastaĵo"
fr = "NOM céréale ; riz, blé, orge, maïs, avoine ; pain, pâtes"

[recognition]
2020-04 = 96
2022-08 = 98
2023-09 = 99
