author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "pre-pu"
coined_year = "<2001"
see_also = ["pona"]
sitelen_emosi = "🧘"
sitelen_pona = ["pasila"]
sitelen_sitelen = ""
source_language = "multiple possibilities"
ucsur = ""
usage_category = "obscure"
word = "pasila"

[[etymology]]
word = "facile"

[luka_pona]

[recognition]
2020-04 = 25
2021-10 = 31
2022-08 = 4
2023-09 = 3
