author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2002"
see_also = ["sama"]
sitelen_emosi = "👯‍♀️"
sitelen_pona = ["pata"]
sitelen_sitelen = ""
source_language = "multiple possibilities"
ucsur = ""
usage_category = "obscure"
word = "pata"

[[etymology]]
alt = "brat"
word = "брат"

[[etymology]]
word = "brata"

[[etymology]]
word = "brother"

[ku_data]
cousin = 6
sibling = 7

[luka_pona]

[recognition]
2020-04 = 28
2021-10 = 36
2022-08 = 5
2023-09 = 4
