author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["laso"]
source_language = "Esperanto"
usage_category = "obscure"
word = "peta"

[[etymology]]
word = "verda"

[recognition]
2020-04 = 13
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = "🟢"
sitelen_pona = ["peta"]
sitelen_sitelen = ""
ucsur = ""
