author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2017"
see_also = []
sitelen_emosi = "😭"
sitelen_pona = ["peto"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "peto"

[[etymology]]
word = "pana e telo oko"

[ku_data]
cry = 7

[luka_pona]

[recognition]
2020-04 = 20
2021-10 = 28
2022-08 = 3
2023-09 = 2
