author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "⏹️"
sitelen_pona = ["pi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/pi.jpg"
source_language = "Tok Pisin"
ucsur = "U+F194D"
usage_category = "core"
word = "pi"

[[etymology]]
word = "bilong"

[ku_data]
about = 9
concerning = 20

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/pi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/pi.mp4"

[pu_verbatim]
de = "PARTIKEL von, des, der (teils wie Genitiv)"
en = "PARTICLE of"
eo = "PARTIKULO de"
fr = "PARTICULE de"

[recognition]
2022-08 = 98
2023-09 = 99
