author_verbatim = "MOD. electric, electronic, conductive, mashinical, online\nN. electricity, lightning, thunder, network\nV. struck by electric/lightning"
author_verbatim_source = "https://www.reddit.com/r/tokipona/comments/mibo62/a_new_word_about_network_electric/"
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["linluwi", "ilo"]
sitelen_emosi = ""
sitelen_pona = ["pika"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "obscure"
word = "pika"

[[etymology]]
alt = "Pikachū"
word = "ピカチュウ"

[luka_pona]

[recognition]
2022-08 = 2
2023-09 = 5
