author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["suno", "walo"]
source_language = "Finnish"
usage_category = "core"
word = "pimeja"

[[etymology]]
word = "pimeä"

[ku_data]
black = 100
dark = 100
darkness = 100
shade = 47
shadow = 50

[pu_verbatim]
de = "ADJEKTIV schwarz, dunkel, unbeleuchtet"
en = "ADJECTIVE black, dark, unlit"
eo = "ADJEKTIVO nigra, malhela, malluma"
fr = "ADJECTIF noir, foncé, sombre"

[recognition]
2022-08 = 99
2023-09 = 100

[representations]
sitelen_emosi = "⚫"
sitelen_pona = ["pimeja"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/pimeja.jpg"
ucsur = "U+F194F"
