author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["Pingo"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "obscure"
word = "Pingo"

[ku_data]
car = 6

[luka_pona]

[recognition]
2021-10 = 20
2022-08 = 5
2023-09 = 4
