author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["open", "kama"]
sitelen_emosi = "🏁"
sitelen_pona = ["pini"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/pini.jpg"
source_language = "multiple possibilities"
ucsur = "U+F1950"
usage_category = "core"
word = "pini"

[ku_data]
cancel = 43
cease = 70
"close (v)" = 65
closed = 64
complete = 47
conclude = 70
conclusion = 40
end = 100
ending = 80
final = 50
finish = 94
interrupt = 32
latter = 55
lock = 30
off = 44
outcome = 70
over = 29
pause = 33
previous = 36
quit = 55
result = 40
shut = 87
stop = 47

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/pini.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/pini.mp4"

[pu_verbatim]
de = "ADJEKTIV vorbei, vollendet, beendet, geendet, vergangen"
en = "ADJECTIVE ago, completed, ended, finished, past"
eo = "ADJEKTIVO antaŭa, finfarita, finita, finiĝinta, pasinta"
fr = "ADJECTIF fini, passé, terminé"

[recognition]
2022-08 = 99
2023-09 = 100
