author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🐞"
sitelen_pona = ["pipi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/pipi.jpg"
source_language = "Acadian French"
ucsur = "U+F1951"
usage_category = "core"
word = "pipi"

[[etymology]]
word = "bibitte"

[ku_data]
bug = 100
insect = 92
spider = 48

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/pipi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/pipi.mp4"

[pu_verbatim]
de = "NOMEN Käfer, Insekt, Ameise, Spinne"
en = "NOUN bug, insect, ant, spider"
eo = "SUBSTANTIVO insekto, formiko, araneo, eta senvertebrulo"
fr = "NOM insecte, araignée, fourmi"

[recognition]
2022-08 = 98
2023-09 = 99
