author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = []
source_language = "toki pona"
usage_category = "obscure"
word = "pipo"

[[etymology]]
word = "pipi"

[recognition]
2020-04 = 19
2021-10 = 21
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = "😒"
sitelen_pona = ["pipo"]
sitelen_sitelen = ""
ucsur = ""
