author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["mute"]
sitelen_emosi = "🍀"
sitelen_pona = ["po"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "po"

[ku_data]
four = 10

[luka_pona]

[recognition]
2020-04 = 25
2021-10 = 34
2022-08 = 5
2023-09 = 5
