author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["lon"]
sitelen_emosi = "↔️"
sitelen_pona = ["poka"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/poka.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F1952"
usage_category = "core"
word = "poka"

[[etymology]]
alt = "бока"
word = "boka"

[ku_data]
alongside = 25
aside = 45
beside = 57
closely = 40
hip = 67
"left (not right)" = 25
side = 100
sidebar = 25

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/poka.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/poka.mp4"

[pu_verbatim]
de = "NOMEN Hüfte, Seite; nah bei, in der Nähe, Umgebung"
en = "NOUN hip, side; next to, nearby, vicinity"
eo = "SUBSTANTIVO kokso, flanko; apud, proksime de, proksimaĵo"
fr = "NOM hanche, côté ; proximité"

[recognition]
2022-08 = 98
2023-09 = 99
