author_verbatim = "pony"
author_verbatim_source = "https://discord.com/channels/301377942062366741/599425762990358528/785585101638860800"
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["soweli"]
sitelen_emosi = ""
sitelen_pona = ["poni"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "poni"

[[etymology]]
word = "pony"

[recognition]
2022-08 = 1
2023-09 = 2
