author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2021"
see_also = ["suwi", "ko"]
sitelen_emosi = "☁️"
sitelen_pona = ["puwa"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "rare"
word = "puwa"

[[etymology]]
alt = "fuwafuwa"
word = "ふわふわ"

[recognition]
2021-10 = 31
2022-08 = 14
2023-09 = 17
