author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2018"
see_also = ["nimisin"]
sitelen_emosi = "✍️"
sitelen_pona = ["samu"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "samu"

[[etymology]]
word = "jan Samu"

[ku_data]
"wanting to create new words" = 40

[recognition]
2020-04 = 16
2021-10 = 29
2022-08 = 3
2023-09 = 1
