author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
source_language = "Esperanto"
usage_category = "core"
word = "selo"

[[etymology]]
word = "ŝelo"

[ku_data]
appearance = 17
barrier = 22
border = 32
boundary = 65
cover = 21
edge = 40
external = 36
frame = 30
layer = 42
margin = 29
outer = 50
outline = 40
peel = 50
shape = 44
shell = 27
skin = 83
surface = 60

[pu_verbatim]
de = "NOMEN äußere Form, äußere Schicht; Rinde, Schale, Hülle, Haut; Grenzfläche, Grenzlinie"
en = "NOUN outer form, outer layer; bark, peel, shell, skin; boundary"
eo = "SUBSTANTIVO ekstera formo, ekstera tavolo; ŝelo (de arbo, frukto, molusko), karapaco, haŭto; limo"
fr = "NOM forme, couche extérieure, peau, écorce, pelure, peau, coquille ; limite"

[recognition]
2022-08 = 98
2023-09 = 98

[representations]
sitelen_emosi = "🔲"
sitelen_pona = ["selo"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/selo.jpg"
ucsur = "U+F1958"
