author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "❓"
sitelen_pona = ["seme"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/seme.jpg"
source_language = "Mandarin"
ucsur = "U+F1959"
usage_category = "core"
word = "seme"

[ku_data]
huh = 44
what = 100
which = 69

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/seme.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/seme.mp4"

[pu_verbatim]
de = "PARTIKEL was? welche? welcher? welches?"
en = "PARTICLE what? which?"
eo = "PARTIKULO kio? kiu?"
fr = "PARTICULE quoi ? quel ?"

[recognition]
2022-08 = 100
2023-09 = 100
