author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["epiku"]
source_language = "English"
usage_category = "obscure"
word = "sikomo"

[[etymology]]
word = "sicko mode"

[recognition]
2020-04 = 19
2021-10 = 22
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = "🤩"
sitelen_pona = ["sikomo"]
sitelen_sitelen = ""
ucsur = ""
