author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "👉"
sitelen_pona = ["sina"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/sina.jpg"
source_language = "Finnish"
ucsur = "U+F195E"
usage_category = "core"
word = "sina"

[[etymology]]
word = "sinä"

[ku_data]
you = 94
your = 88
yours = 83
yourself = 67

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/sina.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/sina.mp4"

[pu_verbatim]
de = "NOMEN du, Sie, ihr"
en = "NOUN you"
eo = "SUBSTANTIVO vi"
fr = "NOM tu, toi, vous"

[recognition]
2022-08 = 100
2023-09 = 100
