author_verbatim = "I thought of another word which would mean the \"ego\", \"self\", \"own\",because Toki Pona doesn't have reflexive voice and pronoun like inthe sentences \"he's watching himself (and not somebody else)\" or \"Hetake his own(not her) hand\". I called it \"sipi\" (as it is \"sibi\" inLatin). Then it would be \"ona li lukin e sipi (pi ona)\" (he watcheshis ego) and \"ona li jo e luka sipi (pi ona)\" (he takes his ego'shand). It would also be used to compound words like \"egoism\"(nasin/pilin sipi) and so on...What do you think?"
author_verbatim_source = "http://forums.tokipona.org/viewtopic.php?f=33&t=639&hilit=word+requests&sid=401a37e08cc5150e7a0738d068ea4a77&start=50#p2368"
book = "none"
coined_era = "pre-pu"
coined_year = "2007"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["sipi"]
sitelen_sitelen = ""
source_language = "Latin"
ucsur = ""
usage_category = "obscure"
word = "sipi"

[[etymology]]
word = "sibi (dative reflexive pronoun)"

[recognition]
2022-08 = 0
2023-09 = 1
