author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["lape"]
source_language = "multiple"
usage_category = "obscure"
word = "slape"

[[etymology]]
word = "lape"

[recognition]
2020-04 = 12
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["slape"]
sitelen_sitelen = ""
ucsur = ""
