author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🧠"
sitelen_pona = ["sona"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/sona.jpg"
source_language = "Georgian"
ucsur = "U+F1961"
usage_category = "core"
word = "sona"

[ku_data]
acknowledge = 25
aware = 83
awareness = 68
clever = 27
cognitive = 27
conscious = 27
data = 60
educational = 28
experienced = 33
expertise = 42
familiar = 27
identify = 28
info = 79
information = 100
insight = 31
intelligence = 40
know = 100
knowledge = 100
known = 62
logic = 25
logical = 27
recognition = 55
recognize = 50
remember = 27
skill = 25
smart = 38
sure = 36
understand = 94
understanding = 93
wisdom = 73
wise = 58

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/sona.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/sona.mp4"

[pu_verbatim]
de = "VERB wissen, qualifiziert sein in, weise sein über, Informationen\nHILFSVERB wissen wie man etw. tut"
en = "VERB to know, be skilled in, be wise about, have information on\nPRE-VERB to know how to"
eo = "VERBO scii, koni, esti lerta pri, esti saĝa pri, havi informojn pri\nANTAŬVERBO scipovi"
fr = "VERBE savoir, connaître\nAUXILIAIRE savoir"

[recognition]
2022-08 = 100
2023-09 = 100
