author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["poka", "teje"]
sitelen_emosi = "🤛"
sitelen_pona = ["soto"]
sitelen_sitelen = ""
source_language = "Swahili"
ucsur = ""
usage_category = "obscure"
word = "soto"

[ku_data]
"left (not right)" = 8

[luka_pona]

[recognition]
2020-04 = 22
2021-10 = 34
2022-08 = 8
2023-09 = 6
