author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["sinpin"]
sitelen_emosi = "🛏️"
sitelen_pona = ["supa"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/supa.jpg"
source_language = "Esperanto"
ucsur = "U+F1965"
usage_category = "core"
word = "supa"

[ku_data]
bench = 38
board = 67
chair = 29
couch = 40
counter = 28
deck = 40
desk = 43
flat = 47
furniture = 50
level = 44
"lie (be in flat position)" = 47
pad = 25
platform = 86
seat = 38
shelf = 80
stage = 38
surface = 30
table = 83
tablet = 33

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/supa.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/supa.mp4"

[pu_verbatim]
de = "NOMEN horizontale Oberfläche, Ding auf dem man etw. ablegt"
en = "NOUN horizontal surface, thing to put or rest something on"
eo = "SUBSTANTIVO horizontala surfaco, io sur kio oni metas ion alian"
fr = "NOM surface horizontale sur laquelle on pose quelque chose"

[recognition]
2022-08 = 98
2023-09 = 99
