author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["pona"]
sitelen_emosi = "🍭"
sitelen_pona = ["suwi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/suwi.jpg"
source_language = "Tok Pisin"
ucsur = "U+F1966"
usage_category = "core"
word = "suwi"

[[etymology]]
word = "swit"

[ku_data]
candy = 65
cute = 92
darling = 26
dessert = 32
gentle = 33
soft = 27
sugar = 58
sweet = 100
tender = 31
treat = 25

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/suwi.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/suwi.mp4"

[pu_verbatim]
de = "ADJEKTIV süß, wohlriechend; niedlich, unschuldig, liebenswert"
en = "ADJECTIVE sweet, fragrant; cute, innocent, adorable"
eo = "ADJEKTIVO dolĉa, bonodora; ĉarma, senkulpa, aminda"
fr = "ADJECTIF doux, parfumé, mignon, innocent, adorable"

[recognition]
2022-08 = 100
2023-09 = 100
