author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["wan", "wile"]
source_language = "Korean"
usage_category = "rare"
word = "taki"

[[etymology]]
alt = "tag"
word = "탁"

[ku_data]
attach = 8
attract = 8
bond = 10
clip = 4

[recognition]
2021-10 = 38
2022-08 = 14
2023-09 = 14

[representations]
sitelen_emosi = ""
sitelen_pona = ["taki", "taki2"]
sitelen_sitelen = ""
ucsur = ""
