author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🤔"
sitelen_pona = ["taso"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/taso.jpg"
source_language = "Tok Pisin"
ucsur = "U+F1968"
usage_category = "core"
word = "taso"

[ku_data]
although = 80
but = 100
despite = 69
except = 53
exception = 27
exclusive = 70
exclusively = 80
however = 82
just = 71
mere = 64
merely = 58
nevertheless = 50
nonetheless = 67
only = 100
regardless = 33
sole = 50
solely = 82
though = 79
whereas = 45
yet = 50

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/taso.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/taso.mp4"

[pu_verbatim]
de = "PARTIKEL aber, jedoch\nADJEKTIV nur, lediglich, alleinig"
en = "PARTICLE but, however\nADJECTIVE only"
eo = "PARTIKULO sed, tamen\nADJEKTIVO nur"
fr = "PARTICULE mais, cependant\nADJECTIF seulement"

[recognition]
2022-08 = 99
2023-09 = 99
