author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["to"]
source_language = "Japanese"
usage_category = "rare"
word = "te"

[[etymology]]
alt = "tte"
word = "って"

[ku_data]
"(opening quotation particle)" = 7

[recognition]
2020-04 = 22
2021-10 = 40
2022-08 = 11
2023-09 = 14

[representations]
sitelen_emosi = "🤜"
sitelen_pona = ["te"]
sitelen_sitelen = ""
ucsur = ""
