author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["poka", "soto"]
sitelen_emosi = ""
sitelen_pona = ["teje"]
sitelen_sitelen = ""
source_language = "Welsh"
ucsur = ""
usage_category = "obscure"
word = "teje"

[[etymology]]
word = "de"

[ku_data]
"right (not left)" = 9

[luka_pona]

[recognition]
2021-10 = 34
2022-08 = 8
2023-09 = 6
