author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["lon"]
sitelen_emosi = "⏰"
sitelen_pona = ["tenpo"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/tenpo.jpg"
source_language = "Esperanto"
ucsur = "U+F196B"
usage_category = "core"
word = "tenpo"

[[etymology]]
word = "tempo"

[ku_data]
appointment = 44
circumstance = 50
date = 50
event = 40
hour = 47
instance = 25
interval = 31
moment = 56
occasion = 65
period = 38
phase = 64
scenario = 42
season = 39
session = 71
situation = 31
time = 100
timing = 72

[pu_verbatim]
de = "NOMEN Zeit, Dauer, Moment, Gelegenheit, Zeitraum, Situation"
en = "NOUN time, duration, moment, occasion, period, situation"
eo = "SUBSTANTIVO tempo, daŭro, momento, okazo, fojo, periodo, situacio"
fr = "NOM temps, durée, moment, occasion, période, situation"

[recognition]
2022-08 = 100
2023-09 = 100
