author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["te"]
sitelen_emosi = ""
sitelen_pona = ["to"]
sitelen_sitelen = ""
source_language = "Japanese"
ucsur = ""
usage_category = "rare"
word = "to"

[ku_data]
"(closing quotation particle)" = 7

[luka_pona]

[recognition]
2021-10 = 38
2022-08 = 11
2023-09 = 14
