author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["tokana"]
sitelen_sitelen = ""
source_language = "Tongan"
ucsur = ""
usage_category = "obscure"
word = "tokana"

[luka_pona]

[recognition]
2021-10 = 18
2022-08 = 1
2023-09 = 2
