author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = []
source_language = "Tongan"
usage_category = "obscure"
word = "tokana"

[[etymology]]
word = "tokanga"

[recognition]
2021-10 = 18
2022-08 = 1
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = ["tokana"]
sitelen_sitelen = ""
ucsur = ""
