author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
source_language = "toki pona"
usage_category = "obscure"
word = "toma"

[[etymology]]
word = "typo of tomo"

[recognition]
2021-10 = 3
2022-08 = 0
2023-09 = 0

[representations]
sitelen_emosi = ""
sitelen_pona = ["toma"]
sitelen_sitelen = ""
ucsur = ""
