author_verbatim = ""
author_verbatim_source = ""
book = "ku suli"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["meli", "mije", "kule"]
sitelen_emosi = "♐"
sitelen_pona = ["tonsi"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/tonsi.jpg"
source_language = "Mandarin"
ucsur = "U+F197E"
usage_category = "widespread"
word = "tonsi"

[ku_data]
"gender non-conforming person" = 53
"intersex person" = 36
"non-binary person" = 59
"transgender person" = 56

[luka_pona]

[recognition]
2020-04 = 57
2021-10 = 89
2022-08 = 86
2023-09 = 83
