author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["kipisi"]
sitelen_emosi = "✌️"
sitelen_pona = ["tu"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/tu.jpg"
source_language = "multiple"
ucsur = "U+F196E"
usage_category = "core"
word = "tu"

[ku_data]
both = 64
couple = 50
cut = 38
divide = 35
double = 80
pair = 88
twice = 50
two = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/tu.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/tu.mp4"

[pu_verbatim]
de = "ZAHL Zwei"
en = "NUMBER two"
eo = "NOMBRO du"
fr = "NOMBRE deux"

[recognition]
2020-04 = 99
2022-08 = 99
2023-09 = 100
