author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "pre-pu"
coined_year = "2001"
see_also = ["san"]
sitelen_emosi = "☘️"
sitelen_pona = ["tuli"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "tuli"

[luka_pona]

[recognition]
2020-04 = 26
2021-10 = 31
2022-08 = 4
2023-09 = 2
