author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
sitelen_emosi = ""
sitelen_pona = ["u"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "obscure"
word = "u"

[luka_pona]

[recognition]
2021-10 = 28
2022-08 = 1
2023-09 = 1
