author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2021"
see_also = []
source_language = "a priori"
usage_category = "obscure"
word = "u"

[[etymology]]

[recognition]
2021-10 = 28
2022-08 = 1
2023-09 = 1

[representations]
sitelen_emosi = ""
sitelen_pona = ["u"]
sitelen_sitelen = ""
ucsur = ""
