author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["laso", "loje", "pimeja"]
sitelen_emosi = ""
sitelen_pona = ["unu"]
sitelen_sitelen = ""
source_language = "Malay-Indonesian"
ucsur = ""
usage_category = "rare"
word = "unu"

[[etymology]]
word = "ungu"

[ku_data]
purple = 27

[luka_pona]

[recognition]
2021-10 = 43
2022-08 = 12
2023-09 = 16
