author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["wawa", "nasa", "ken"]
sitelen_emosi = ""
sitelen_pona = ["usawi"]
sitelen_sitelen = ""
source_language = "Swahili"
ucsur = ""
usage_category = "uncommon"
word = "usawi"

[[etymology]]
word = "uchawi"

[ku_data]
magic = 7

[recognition]
2021-10 = 41
2022-08 = 16
2023-09 = 22
