author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "👄"
sitelen_pona = ["uta", "uta2"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/uta.jpg"
source_language = "Serbo-Croatian"
ucsur = "U+F1970"
usage_category = "core"
word = "uta"

[ku_data]
bite = 31
chew = 25
jaw = 42
kiss = 44
lip = 47
mouth = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/uta.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/uta.mp4"

[pu_verbatim]
de = "NOMEN Mund, Lippen, Mundhöhle, Kiefer"
en = "NOUN mouth,lips, oral cavity, jaw"
eo = "SUBSTANTIVO buŝo, lipoj, buŝa kavo, makzeloj"
fr = "NOM bouche, lèvres, cavité buccale, mâchoire"

[recognition]
2022-08 = 98
2023-09 = 99
