author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["tenpo"]
sitelen_emosi = "ℹ️"
sitelen_pona = ["waleja"]
sitelen_sitelen = ""
source_language = "Quenya"
ucsur = ""
usage_category = "obscure"
word = "waleja"

[[etymology]]
word = "valdea"

[ku_data]
attention = 10
background = 8
case = 5
circumstance = 14
context = 15
emphasis = 7
emphasize = 8
premise = 4
situation = 8
subject = 4
theme = 9
topic = 6

[recognition]
2020-04 = 19
2021-10 = 34
2022-08 = 5
2023-09 = 3
