author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["pimeja"]
sitelen_emosi = "⚪"
sitelen_pona = ["walo"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/walo.jpg"
source_language = "Finnish"
ucsur = "U+F1972"
usage_category = "core"
word = "walo"

[ku_data]
pale = 74
white = 100

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/walo.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/walo.mp4"

[pu_verbatim]
de = "ADJEKTIV weiß, weißlich; hellfarbig, blass"
en = "ADJECTIVE white, whitish; light-coloured, pale"
eo = "ADJEKTIVO blanka, blankeca; helkolora, pala"
fr = "ADJECTIF blanc, clair, pâle"

[recognition]
2022-08 = 98
2023-09 = 100
