author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = ["pimeja"]
source_language = "Finnish"
usage_category = "core"
word = "walo"

[[etymology]]
word = "valko"

[ku_data]
pale = 74
white = 100

[pu_verbatim]
de = "ADJEKTIV weiß, weißlich; hellfarbig, blass"
en = "ADJECTIVE white, whitish; light-coloured, pale"
eo = "ADJEKTIVO blanka, blankeca; helkolora, pala"
fr = "ADJECTIF blanc, clair, pâle"

[recognition]
2022-08 = 98
2023-09 = 100

[representations]
sitelen_emosi = "⚪"
sitelen_pona = ["walo"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/walo.jpg"
ucsur = "U+F1972"
