author_verbatim = "In my Caves of Qud mod, I added toki-pona-speaking bird-beasts who call themselves \"wasoweli\"; I figured as 'native speakers' they're entitled to a portmanteau noun for themselves, and that's the only intentional artistic liberty I took with the language."
author_verbatim_source = "https://discord.com/channels/301377942062366741/301378960468738050/690041651397132345"
book = "ku lili"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["waso", "soweli", "sutopatikuna"]
sitelen_emosi = ""
sitelen_pona = ["wasoweli"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "wasoweli"

[[etymology]]
word = "waso + soweli"

[luka_pona]

[recognition]
2021-10 = 22
2022-08 = 3
2023-09 = 6
