author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "🦅"
sitelen_pona = ["waso"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/waso.jpg"
source_language = "Acadian French"
ucsur = "U+F1974"
usage_category = "core"
word = "waso"

[[etymology]]
word = "oiseau"

[ku_data]
bat = 23
bird = 100
chicken = 44
duck = 40
eagle = 30
turkey = 33

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/waso.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/waso.mp4"

[pu_verbatim]
de = "NOMEN Vogel, fliegende Kreatur, geflügeltes Tier"
en = "NOUN bird, flying creature, winged animal"
eo = "SUBSTANTIVO birdo, fluganta vivaĵo, besto kun flugiloj"
fr = "NOM oiseau, créature volante, animal ailé"

[recognition]
2022-08 = 99
2023-09 = 99
