author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
see_also = []
sitelen_emosi = "⚡"
sitelen_pona = ["wawa"]
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/wawa.jpg"
source_language = "Finnish"
ucsur = "U+F1975"
usage_category = "core"
word = "wawa"

[[etymology]]
word = "vahva"

[ku_data]
bold = 68
boost = 25
brave = 47
charge = 53
compelling = 27
confident = 27
electrical = 42
electricity = 33
energy = 88
fast = 30
firmly = 62
force = 73
glory = 25
intense = 71
intensity = 65
might = 40
power = 100
powerful = 92
quickly = 27
rapid = 42
rapidly = 30
reinforce = 63
severe = 25
strength = 100
strengthen = 62
strong = 88
strongly = 82
tough = 35

[luka_pona]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/wawa.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/wawa.mp4"

[pu_verbatim]
de = "ADJEKTIV stark, kräftig; zuversichtlich, sicher; energetisch, intensiv"
en = "ADJECTIVE strong, powerful; confident, sure; energetic, intense"
eo = "ADJEKTIVO forta, potenca; memfida, nedubanta; energia, intensa"
fr = "ADJECTIF fort, puissant ; sûr, confiant ; énergique, intense"

[recognition]
2022-08 = 99
2023-09 = 100
