author_verbatim = "•Something that appears to break the rules but doesn't\n•Faux edginess\n•Provocation"
author_verbatim_source = "https://discord.com/channels/301377942062366741/375591429608570881/556942279227736064"
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = ["wuwojiti"]
sitelen_emosi = "🤡"
sitelen_pona = ["wawajete"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "wawajete"

[[etymology]]
word = "wuwojiti"

[luka_pona]

[recognition]
2020-04 = 18
2021-10 = 24
2022-08 = 2
2023-09 = 4
