author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-ku"
coined_year = "2022"
see_also = []
source_language = "Spanish"
usage_category = "obscure"
word = "we"

[[etymology]]
word = "güey"

[recognition]
2023-09 = 2

[representations]
sitelen_emosi = ""
sitelen_pona = []
sitelen_sitelen = ""
ucsur = ""
