author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
sitelen_emosi = "🔒"
sitelen_pona = ["we"]
sitelen_sitelen = ""
source_language = "Spanish"
ucsur = ""
usage_category = "obscure"
word = "we"

[[etymology]]
word = "güey"

[luka_pona]

[recognition]
2021-10 = 19
2022-08 = 1
2023-09 = 1
