author_verbatim = "also, when i meant wekama, i meant weka, then kama"
author_verbatim_source = "https://discord.com/channels/301377942062366741/545467374254555137/732119749114331148"
book = "none"
coined_era = "post-pu"
coined_year = "2020"
see_also = ["weka", "kama"]
sitelen_emosi = ""
sitelen_pona = ["wekama"]
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "obscure"
word = "wekama"

[[etymology]]
word = "weka kama"

[luka_pona]

[recognition]
2021-10 = 25
2022-08 = 5
2023-09 = 5
