author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2017"
see_also = ["mi"]
sitelen_emosi = "🙋"
sitelen_pona = ["wi"]
sitelen_sitelen = ""
source_language = "English"
ucsur = ""
usage_category = "obscure"
word = "wi"

[[etymology]]
word = "we"

[luka_pona]

[recognition]
2020-04 = 14
2022-08 = 0
2023-09 = 1
