author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2018"
see_also = []
sitelen_emosi = ""
sitelen_pona = []
sitelen_sitelen = ""
source_language = "toki pona"
ucsur = ""
usage_category = "uncommon"
word = "wuwojiti"

[luka_pona]

[recognition]
2022-08 = 13
2023-09 = 22
