author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2018"
see_also = []
source_language = "toki pona"
usage_category = "uncommon"
word = "wuwojiti"

[[etymology]]
word = "wu"

[recognition]
2022-08 = 13
2023-09 = 22

[representations]
sitelen_emosi = ""
sitelen_pona = []
sitelen_sitelen = ""
ucsur = ""
