author_verbatim = ""
author_verbatim_source = ""
book = "ku lili"
coined_era = "post-pu"
coined_year = "2019"
see_also = []
sitelen_emosi = "📉"
sitelen_pona = ["yupekosi"]
sitelen_sitelen = ""
source_language = "a priori"
ucsur = ""
usage_category = "uncommon"
word = "yupekosi"

[ku_data]
"change a creative work and unintentionally make it worse" = 50

[luka_pona]

[recognition]
2020-04 = 27
2021-10 = 40
2022-08 = 16
2023-09 = 22
