author_verbatim = "discord star emoji"
author_verbatim_source = "https://discord.com/channels/301377942062366741/873076683937284106/873586280603189248"
book = "none"
coined_era = "post-ku"
coined_year = "2021"
see_also = ["mun"]
sitelen_emosi = ""
sitelen_pona = ["yutu"]
sitelen_sitelen = ""
source_language = "Turkish"
ucsur = ""
usage_category = "obscure"
word = "yutu"

[[etymology]]
word = "yıldız"

[recognition]
2022-08 = 3
2023-09 = 2
