name: Generate JSON Schemas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schemas
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
              cwd: ./schemas

      - name: Generate JSON Schemas
        run: pnpm run generate:schemas

      - name: Commit schemas
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated schemas for ${{ github.event.pull_request.head.sha || github.event.head_commit.id || vars.GITHUB_SHA }}"

      - name: Validate TOMLs for the new schemas
        uses: ./.github/workflows/validate_toml.yml
        if: ${{ steps.commit.outputs.committed }}
