name: Package TOMLs into JSON

on:
  workflow_call:

  workflow_dispatch:

permissions: 
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: pip install tomlkit && npm i -g ajv-cli ajv-formats

      - name: Generate raw data file
        run: python .github/workflows/package_data.py

      - name: Validate generated file
        run: |
          npx ajv-cli -s ./schemas/generated/words.json -c ajv-formats --errors=text -d ./raw/words.json
          npx ajv-cli -s ./schemas/generated/luka_pona.json -c ajv-formats --errors=text -d ./raw/luka_pona.json

      - name: Commit packaged files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated data.json for ${{ github.sha }}"
