name: Validate TOML Files

on:
  push:
    paths:
      - "**.toml"
      - "schemas/schema.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate definition files
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{github.event.ref}}/schemas/schema.json#definition ./translations/**/definitions.toml

      - name: Validate commentary files
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{github.event.ref}}/schemas/schema.json#commentary ./translations/**/commentary.toml

      - name: Validate etymology files
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{github.event.ref}}/schemas/schema.json#etymology ./translations/**/etymology.toml

      - name: Validate sitelen pona files
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{github.event.ref}}/schemas/schema.json#sitelen_pona ./translations/**/sp_etymology.toml

      - name: Validate word files
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{github.event.ref}}/schemas/schema.json#word ./words/*.toml
