name: Validate TOML Files

on:
  workflow_run:
    workflows: ["Generate JSON Schemas"]
    types: ["completed"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate translations
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{vars.GITHUB_SHA || 'main'}}/schemas/schema.json#translation ./translations/*.toml

      - name: Validate words.toml
        run: npx --yes @taplo/cli check --schema https://raw.githubusercontent.com/lipu-linku/sona/${{vars.GITHUB_SHA || 'main'}}/schemas/schema.json#word ./words/*.toml
